// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.NEXT_PUBLIC_SUPABASE_URL || "https://pgecpyylurtpvdjktbuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZWNweXlsdXJ0cHZkamt0YnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3MTIyNDYsImV4cCI6MjA5NDI4ODI0Nn0.OeE6gVQ1eMURCzf10F5zFn6ODm1BA4IDXO_0lEphqt8";

if (!SUPABASE_URL || SUPABASE_URL === "https://placeholder.supabase.co" || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ ERROR: Configuración de Supabase faltante. Verifica las variables de entorno VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY.");
}

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 

  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);